baseURL = "http://nav.pokeai.cn/"
languageCode = "zh-CN"
title = "破壳Ai 信息站"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "iplaycode"
  description = "Webstack Hugo"
them = "webstack-hugo"
